# Generated by Django 2.2 on 2019-04-08 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Talk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('speaker', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('number_of_views', models.PositiveIntegerField()),
                ('transcript', models.TextField()),
            ],
        ),
    ]
